### ISSUE TITLE
修改编码

### ISSUE THREAD

**Issue by B0y1n4o4** [dzlzh/shiyanlou-courses#1]
代码高亮处存在编码变换．例如`&lt; ` `&gt;` 等．希望能够修改！感谢作者的倾心付出．

**Comment by dzlzh** [comment]
:joy: 我也发现了， 一直没什么时间改。会抽时间改一下
其实有完全可去实验楼体验全部的功能

**Comment by B0y1n4o4** [comment]
@dzlzh , 可以进行批量替换．sed命令．就不用一个一个去修改了．

**Comment by dzlzh** [comment]
@greenhand2learn 已经修改完了,如果有发现没发修改的可以给我提交 issues 或者 pull request
